### PR TITLE
Add missing deps

### PR DESCRIPTION
**Pull request by szepeviktor**
@mattrothenberg Please update the lock file.

### CODE REVIEW

**Comment by mattrothenberg** [comment]
Hi @szepeviktor, can you please explain why `erusev/parsedown` is a dependency?

**Comment by szepeviktor** [comment]
statmic depends on it, and it needs a beta release.

**Comment by mattrothenberg** [comment]
@szepeviktor Right, but I'm confused because:

1. This addon installs totally fine in a fresh Statamic project, without warnings or errors.
2. Why would we need to specify a _Statamic_ dependency in this completely separate module?

**Comment by szepeviktor** [comment]
As this addon is not able to run without statamic, and it may need a specific version of statamic.

Although I've just realized this is not a custom in the statamic ecosystem.

**Comment by szepeviktor** [comment]
I see!
There is such a thing as `"type": "statamic-addon",`

**Pull request closed without merging**
